### ISSUE TITLE
Добавление функционала

### ISSUE THREAD

**Issue by iponosov** [stleon/graffiti_map#3]
Необходимо предусмотреть функционал:
- [x] Код вставки карты на сайт/блог
- [x]  В админке вставить карту и определение координат
- [x] Уведомление администрации по email о добавлении новых граффити
- [x] При добавлении граффити резать картинки по максимальной ширине 1024 и конвертировать в ~~png~~ jpg.
- [x] Для добавляемого граффити добавить маркировку типа "легальный/нелегальный", которую выбирает администратор/модератор при утверждении граффити
- [x] Указывать маркировку типа граффити на сайте. Если граффити сделано нелегально, то указывать кол-во дней с момента загрузки и уведомлять о том, что возможно граффити уже уничтожено.
- [x] В дополнение к остальным соц.сетям добавить возможность комментировать через Вконтакте, возможно использовать hypercomments.com
- [x] Уменьшить размер картинок слева, больший акцент на карте.
- [x] Создать страницу пожертвований (на главной кнопку)

**Comment by stleon** [comment]
Я [тут](http://habrahabr.ru/company/io/blog/257533/) прочитал, что лучше все-таки в **jpg**.

**Comment by iponosov** [comment]
ок

**Comment by stleon** [comment]
@iponosov [Страницу пожертвований](http://yasobe.ru/) или [кнопку](https://money.yandex.ru/embed/quickpay/small.xml?from=iget&_openstat=iget%3Bsmall)? 

И где разместить?

**Comment by iponosov** [comment]
думаю пока можно ограничиться страницей, а потом, когда будет подверстывать по дизайну, то можем и кнопку влепить.
