### ISSUE TITLE
добавить слово "возможно" в описание граффити

### ISSUE THREAD

**Issue by GSuvorov** [stleon/graffiti_map#30]
"это граффити было сделано нелегально" заменить на “возможно это граффити было сделано нелегально” , https://www.dropbox.com/s/rgh7xx5ls3tafnw/Screenshot%202015-07-14%2016.20.43.png?dl=0

**Comment by stleon** [comment]
@GSuvorov сейчас там пишется: 

```
Данное граффити сделано нелегально. Время, прошедшее с момента загрузки: N. Возможно, оно уже уничтожено 
```

Если написать:

```
Возможно, данное граффити было сделано нелегально ... Возможно оно уже устарело
```

То получится лексический повтор. 

Давайте, я поменяю на **Скорее всего**
